function PCFooter() {
    document.writeln("<div class=\'container-fluid d-none d-md-block p-0\' style=\'background-color: #003366;\'>");
    document.writeln("        <div class=\'\' id=\'game-v-flex\' style=\'background-image: url(../reb/img/桌機index_img/footer背景-01.png);\'>");
    document.writeln("            <div class=\'container pt-3\'>");
    document.writeln("                <!-- 各廠商 -->");
    document.writeln("                <div class=\'col-12 pt-3 px-0\' style=\'display: flex;justify-content: space-between;\'>");
    document.writeln("                    <a href=\'https://999xc.net/product/allbet-livecasino\' target=\'_blank\'><img class=\'w-100\'");
    document.writeln("                            src=\'../img/桌機index_img/各廠商/1-01.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'https://999xc.net/product/wm-livecasino\' target=\'_blank\'><img class=\'w-100\'");
    document.writeln("                            src=\'../img/桌機index_img/各廠商/1-02.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'https://999xc.net/product/super-lottery\' target=\'_blank\'><img class=\'w-100\'");
    document.writeln("                            src=\'../img/桌機index_img/各廠商/1-03.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'https://999xc.net/product/rtg-slot\' target=\'_blank\'><img class=\'w-100\'");
    document.writeln("                            src=\'../img/桌機index_img/各廠商/1-04.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'#\' target=\'_blank\'><img class=\'w-100\' src=\'../img/桌機index_img/各廠商/1-05.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'https://999xc.net/product/simpleplay-slot\' target=\'_blank\'><img class=\'w-100\'");
    document.writeln("                            src=\'../img/桌機index_img/各廠商/1-06.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'https://999xc.net/product/sa-livecasino\' target=\'_blank\'><img class=\'w-100\'");
    document.writeln("                            src=\'../img/桌機index_img/各廠商/1-07.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'https://999xc.net/product/9k-lottery\' target=\'_blank\'><img class=\'w-100\'");
    document.writeln("                            src=\'../img/桌機index_img/各廠商/1-08.png\' alt=\'\'></a>");
    document.writeln("                </div>");
    document.writeln("                <div class=\'col-12 pt-4 px-0\' style=\'display: flex;justify-content: space-between;\'>");
    document.writeln("                    <a href=\'https://999xc.net/product/bwin-slot\' target=\'_blank\'><img class=\'w-100\'");
    document.writeln("                            src=\'../img/桌機index_img/各廠商/1-09.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'https://999xc.net/product/dg-livecasino\' target=\'_blank\'><img class=\'w-100\'");
    document.writeln("                            src=\'../img/桌機index_img/各廠商/1-10.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'https://999xc.net/product/super-sports\' target=\'_blank\'><img class=\'w-100\'");
    document.writeln("                            src=\'../img/桌機index_img/各廠商/1-11.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'#\' target=\'_blank\'><img class=\'w-100\' src=\'../img/桌機index_img/各廠商/1-12.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'#\' target=\'_blank\'><img class=\'w-100\' src=\'../img/桌機index_img/各廠商/1-13.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'#\' target=\'_blank\'><img class=\'w-100\' src=\'../img/桌機index_img/各廠商/1-14.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'https://999xc.net/product/ka-slot\' target=\'_blank\'><img class=\'w-100 pl-3\'");
    document.writeln("                            src=\'../img/桌機index_img/各廠商/1-15.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'#\' target=\'_blank\'><img class=\'w-100\' src=\'../img/桌機index_img/各廠商/1-16.png\' alt=\'\'></a>");
    document.writeln("                </div>");
    document.writeln("                <!-- 連結 -->");
    document.writeln("                <div class=\'row py-3\'>");
    document.writeln("                    <div class=\'d-flex mx-auto\'>");
    document.writeln("                        <a href=\'../index.html\' class=\'text-light text-center px-3\' style=\'font-size: 1.1rem;\'>娛樂城</a>");
    document.writeln("                        <p class=\'text-light text-center px-3\' style=\'font-size: 1.1rem;\'>|</p>");
    document.writeln("                        <a href=\'./LiveCasino.html\' class=\'text-light text-center px-3\'");
    document.writeln("                            style=\'font-size: 1.1rem;\'>百家樂</a>");
    document.writeln("                        <p class=\'text-light text-center px-3\' style=\'font-size: 1.1rem;\'>|</p>");
    document.writeln("                        <a href=\'./Sport.html\' class=\'text-light text-center px-3\' style=\'font-size: 1.1rem;\'>球版現金版</a>");
    document.writeln("                        <p class=\'text-light text-center px-3\' style=\'font-size: 1.1rem;\'>|</p>");
    document.writeln("                        <a href=\'./Slot.html\' class=\'text-light text-center px-3\' style=\'font-size: 1.1rem;\'>電子拉霸</a>");
    document.writeln("                        <p class=\'text-light text-center px-3\' style=\'font-size: 1.1rem;\'>|</p>");
    document.writeln("                        <a href=\'./Bingo.html\' class=\'text-light text-center px-3\' style=\'font-size: 1.1rem;\'>鑫城賓果</a>");
    document.writeln("                        <p class=\'text-light text-center px-3\' style=\'font-size: 1.1rem;\'>|</p>");
    document.writeln("                        <a href=\'../Features page/BaccaratTechniques.html\' class=\'text-light text-center px-3\'");
    document.writeln("                            style=\'font-size: 1.1rem;\'>百家樂技巧教學</a>");
    document.writeln("                        <p class=\'text-light text-center px-3\' style=\'font-size: 1.1rem;\'>|</p>");
    document.writeln("                        <a href=\'../Features page/AboutUs.html\' class=\'text-light text-center px-3\'");
    document.writeln("                            style=\'font-size: 1.1rem;\'>關於任你博</a>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("                <!-- 字:任你博版權 -->");
    document.writeln("                <div class=\'col-12 pt-2 pb-4\'>");
    document.writeln("                    <p class=\'text-center text-light lp1\'>");
    document.writeln("                        【任你博】所有版權未經本公司合法授權任意復制版權必究</p>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
}
// MD Footer
function MDFooter() {
    document.writeln("<!-- blog -->");
    document.writeln("    <div class=\'container-fluid d-md-none\' style=\'background-color:#bdd5ef;\'>");
    document.writeln("        <div class=\'row mx-2 py-3\'>");
    document.writeln("            <p class=\'col-12 blog-t-color text-center text-monospace\'>任你博娛樂城-線上賭場百家樂推薦</p>");
    document.writeln("            <p class=\'centerCenter w3-small py-3 blog-t-color text-monospace\'>【任你博】所有版權未經本公司合法授權任意復制版權必究</p>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("");
    document.writeln("    <!-- footer h -->");
    document.writeln("    <div class=\'container-fluid d-md-none\' style=\'min-height: 70px;\'></div>");
    document.writeln("");
    document.writeln("    <!-- footer -->");
    document.writeln("    <div class=\'container-fluid d-md-none md-footer-color fixed-bottom\'>");
    document.writeln("        <div class=\'row py-2\'>");
    document.writeln("            <div class=\'col-3 h-100 text-center\'><a href=\'../index.html\'><img src=\'../img/手機index_img/手機最下方/包裝/首頁.png\'");
    document.writeln("                        alt=\'\'></a></div>");
    document.writeln("            <div class=\'col-3 h-100 text-center\'><a href=\'../page/indexLogin.html\'><img");
    document.writeln("                        src=\'../img/手機index_img/手機最下方/包裝/登入.png\' alt=\'\'></a></div>");
    document.writeln("            <div class=\'col-3 h-100 text-center\'><a href=\'../header page/Signup.html\'><img");
    document.writeln("                        src=\'../img/手機index_img/手機最下方/包裝/註冊.png\' alt=\'\'></a></div>");
    document.writeln("            <div class=\'col-3 h-100 text-center\'><a href=\'../page/Promotion.html\'><img");
    document.writeln("                        src=\'../img/手機index_img/手機最下方/包裝/優惠.png\' alt=\'\'></a></div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
}
// page頁面 上方
function PageHeader() {
    document.writeln("<!-- /////////////////////////////////////// 電腦板 ///////////////////////////////////// -->");
    document.writeln("    <!-- login -->");
    document.writeln("    <header>");
    document.writeln("        <div class=\'container-fluid d-none d-md-block p-0\' style=\'background-color:#3fa9f5;\'>");
    document.writeln("            <div class=\'row py-3\'>");
    document.writeln("                <div class=\'flex-grow-1 text-right mr-5\'>");
    document.writeln("                    <input type=\'text\' class=\'px-2 input-style\' placeholder=\'用戶名(ID)\' onfocus=\'this.placeholder = \'\'\'");
    document.writeln("                        onblur=\'this.placeholder = \' 用戶名(ID)\'\' />");
    document.writeln("                    <input type=\'password\' class=\'px-2 input-style\' placeholder=\'密碼\' onfocus=\'this.placeholder = \'\'\'");
    document.writeln("                        onblur=\'this.placeholder = \' 密碼\'\' />");
    document.writeln("                    <a href=\'../page/indexLogin.html\'><input class=\'mx-1 button-login\' type=\'submit\' value=\'登入\'></a>");
    document.writeln("                    <a href=\'../header page/Signup.html\' target=\'_blank\'>");
    document.writeln("                        <input class=\'mx-1 button-registered\' type=\'button\' value=\'註冊\'>");
    document.writeln("                    </a>");
    document.writeln("                </div>");
    document.writeln("                <div class=\'col-lg-4 col-md-12 text-md-right text-lg-left mr-md-5 pr-md-5 pt-md-2 pt-lg-0\'");
    document.writeln("                    style=\'justify-content: space-between;margin-left: -2%;\'>");
    document.writeln("                    <a class=\'text-light mx-1\' href=\'../header page/Announcement.html\'>公告</a>");
    document.writeln("                    <a class=\'text-light mx-1\' href=\'../header page/AppDownload.html\'>APP下載</a>");
    document.writeln("                    <a class=\'text-light mx-1\' href=\'../header page/FAQ.html\'>常見問題</a>");
    document.writeln("                    <a class=\'text-light mx-1\' href=\'../header page/Agent.html\'>合作代理</a>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </header>");
    document.writeln("    <!-- login -->");
    document.writeln("");
    document.writeln("    <div class=\'\' onclick=\'AnimaTion2();\'></div>");
    document.writeln("    <!-- logo & list -->");
    document.writeln("    <div class=\'container-fluid d-none d-lg-block p-0\'");
    document.writeln("        style=\'background: linear-gradient(180deg, #2278E0 0%, #1754A7 100%);\'>");
    document.writeln("        <div class=\'container py-3\'>");
    document.writeln("            <div class=\'row\' style=\'align-items:center;\'>");
    document.writeln("                <div class=\'col-3\'>");
    document.writeln("                    <a class=\'\' href=\'../index.html\'><img class=\'w-100\' src=\'../img/桌機index_img/logo.png\'></a>");
    document.writeln("                </div>");
    document.writeln("                <div class=\'col-9\'>");
    document.writeln("                    <a href=\'../page/LiveCasino.html\' style=\'width: 11.11%;\'><img class=\'AnimaTion AnimaTion1\'");
    document.writeln("                            src=\'../img/桌機index_img/list/list1.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'../page/Sport.html\' style=\'width: 11.11%;\'><img class=\'AnimaTion AnimaTion2\'");
    document.writeln("                            src=\'../img/桌機index_img/list/list2.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'../page/Chess.html\' style=\'width: 11.11%;\'><img class=\'AnimaTion AnimaTion3\'");
    document.writeln("                            src=\'../img/桌機index_img/list/list3.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'../page/Slot.html\' style=\'width: 11.11%;\'><img class=\'AnimaTion AnimaTion4\'");
    document.writeln("                            src=\'../img/桌機index_img/list/list4.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'../page/Bingo.html\' style=\'width: 11.11%;\'><img class=\'AnimaTion AnimaTion5\'");
    document.writeln("                            src=\'../img/桌機index_img/list/list5.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'../page/Fish.html\' style=\'width: 11.11%;\'><img class=\'AnimaTion AnimaTion6\'");
    document.writeln("                            src=\'../img/桌機index_img/list/list6.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'../page/MainPages.html\' style=\'width: 11.11%;\'><img class=\'AnimaTion AnimaTion7\'");
    document.writeln("                            src=\'../img/桌機index_img/list/list7.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'../page/Promotion.html\' style=\'width: 11.11%;\'><img class=\'AnimaTion AnimaTion8\'");
    document.writeln("                            src=\'../img/桌機index_img/list/list8.png\' alt=\'\'></a>");
    document.writeln("                    <a href=\'../page/Movie.html\' style=\'width: 11.11%;\'><img class=\'AnimaTion AnimaTion9\'");
    document.writeln("                            src=\'../img/桌機index_img/list/list9.png\' alt=\'\'></a>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("    ");
    document.writeln("    <script src=\'../js/indexList copy.js\'></script>");
    document.writeln("    <!-- logo & list -->");
    document.writeln("");
    document.writeln("    <!-- /////////////////////////////////////// 手機板header ///////////////////////////////////// -->");
    document.writeln("    <div class=\'container-fluid p-0 d-lg-none \' style=\'background: linear-gradient(180deg, #2278E0 0%, #1754A7 100%);\'>");
    document.writeln("        <div class=\'container\'>");
    document.writeln("            <div class=\'row py-2\' style=\'align-items: center;\'>");
    document.writeln("                <!-- 漢堡圖 -->");
    document.writeln("                <div class=\'col-4 text-left\'>");
    document.writeln("                    <!-- HamburgBtn -->");
    document.writeln("                    <i class=\'fas fa-bars fa-2x text-light\' id=\'HamburgBtn\' data-toggle=\'modal\'");
    document.writeln("                        data-target=\'#exampleModal0\'></i>");
    document.writeln("                    <!--  -->");
    document.writeln("                    <div class=\'modal\' id=\'exampleModal0\'>");
    document.writeln("                        <div id=\'showMenu p-0\' class=\'modal-dialog\'>");
    document.writeln("                            <div class=\'showMenuList modal-content\'>");
    document.writeln("                                <div class=\'modal-body p-0\'>");
    document.writeln("                                    <!-- 關閉 -->");
    document.writeln("                                    <div class=\'w-100\'>");
    document.writeln("                                        <div class=\'pb-2 pt-1 pr-3 text-light text-right\' data-dismiss=\'modal\'><i");
    document.writeln("                                                class=\'fas fa-times text-light\'></i></div>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- user -->");
    document.writeln("                                    <div class=\'col-12 text-center w-100\'>");
    document.writeln("                                        <img src=\'../img/手機index_img/sidebar/user.png\' alt=\'\'>");
    document.writeln("                                        <p class=\'text-center text-light pt-1\' style=\'font-size: 1.2rem;\'>admin</p>");
    document.writeln("                                    </div>");
    document.writeln("                                    <div class=\'sidebarLine w-100\'></div>");
    document.writeln("                                    <div class=\'row\'>");
    document.writeln("                                        <div class=\'col-12 pt-3\'><a href=\'../page/Promotion.html\'><img");
    document.writeln("                                                    src=\'../img/手機index_img/sidebar/Group 2/1gift.png\' alt=\'\'");
    document.writeln("                                                    class=\'pl-3\'><span class=\'text-light pl-3\'>優惠活動</span></a></div>");
    document.writeln("                                        <div class=\'col-12  pt-3\'><a href=\'../header page/Announcement.html\'><img");
    document.writeln("                                                    src=\'../img/手機index_img/sidebar/Group 2/2Shape.png\' alt=\'\'");
    document.writeln("                                                    class=\'pl-3\'><span class=\'text-light pl-3\'>公告</span></a></div>");
    document.writeln("                                        <div class=\'col-12  pt-3\'><a href=\'../header page/FAQ.html\'><img");
    document.writeln("                                                    src=\'../img/手機index_img/sidebar/Group 2/3_question-square-light.png\'");
    document.writeln("                                                    alt=\'\' class=\'pl-3\'><span class=\'text-light pl-3\'>常見問題</span></a>");
    document.writeln("                                        </div>");
    document.writeln("                                        <div class=\'col-12  pt-3\'><a href=\'../Features page/RepairTime.html\'><img");
    document.writeln("                                                    src=\'../img/手機index_img/sidebar/Group 2/4_clock-light.png\' alt=\'\'");
    document.writeln("                                                    class=\'pl-3\'><span class=\'text-light pl-3\'>維修時間</span></a></div>");
    document.writeln("                                        <div class=\'col-12  pt-3\'><a href=\'../header page/AppDownload.html\'><img");
    document.writeln("                                                    src=\'../img/手機index_img/sidebar/Group 2/5cloud-download-light.png\'");
    document.writeln("                                                    alt=\'\' class=\'pl-3\'><span class=\'text-light pl-3\'>APP下載</span></a>");
    document.writeln("                                        </div>");
    document.writeln("                                        <!-- sidebarBLine -->");
    document.writeln("                                        <div class=\' col-12 py-3\'>");
    document.writeln("                                            <div class=\'sidebarBLine\'></div>");
    document.writeln("                                        </div>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- list2 -->");
    document.writeln("                                    <div class=\'row\'>");
    document.writeln("                                        <div class=\'col-12 pt-1\'><a href=\'../Features page/AccessFlow.html\'><img");
    document.writeln("                                                    src=\'../img/手機index_img/sidebar/Group 3/1wallet-light.png\' alt=\'\'");
    document.writeln("                                                    class=\'pl-3\'><span class=\'text-light pl-3\'>存取流程</span></a></div>");
    document.writeln("                                        <div class=\'col-12  pt-3\'><a href=\'../header page/Agent.html\'><img");
    document.writeln("                                                    src=\'../img/手機index_img/sidebar/Group 3/5_cooperation.png\' alt=\'\'");
    document.writeln("                                                    class=\'pl-3\'><span class=\'text-light pl-3\'>合營代理</span></a></div>");
    document.writeln("                                        <div class=\'col-12  pt-3\'><a href=\'../Features page/AboutUs.html\'><img");
    document.writeln("                                                    src=\'../img/手機index_img/sidebar/Group 3/6_RENNIBO1.png\' alt=\'\'");
    document.writeln("                                                    class=\'pl-3\'><span class=\'text-light pl-3\'>關於任你博</span></a></div>");
    document.writeln("                                        <!-- sidebarBLine -->");
    document.writeln("                                        <div class=\' col-12 py-3\'>");
    document.writeln("                                            <div class=\'sidebarBLine\'></div>");
    document.writeln("                                        </div>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- list3 -->");
    document.writeln("                                    <div class=\'row\'>");
    document.writeln("                                        <div class=\'col-12 pt-1\'><a href=\'../index.html\' role=\'button\'><img");
    document.writeln("                                                    src=\'../img/手機index_img/sidebar/signOut.png\' alt=\'\'");
    document.writeln("                                                    class=\'pl-3\'><span class=\'text-light pl-3\'>登出</span></a></div>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                            </div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("                <div class=\'col-4 text-center\'>");
    document.writeln("                    <div class=\'text-center\' style=\'margin-left: -5%;\'><a href=\'../index.html\'><img");
    document.writeln("                                src=\'../img/桌機index_img/logo.png\' alt=\'\' class=\'w-100\'></a></div>");
    document.writeln("                </div>");
    document.writeln("                <!-- 24HR客服 -->");
    document.writeln("                <div class=\'col-4\'>");
    document.writeln("                    <div class=\'text-right\' style=\'margin-right: 10%;\'><img id=\'hrServiceBtn\'");
    document.writeln("                            src=\'../img/手機index_img/24-service.png\' alt=\'\' class=\'h-100\' data-toggle=\'modal\'");
    document.writeln("                            data-target=\'#exampleModal\'></div>");
    document.writeln("                </div>");
    document.writeln("                <!-- Modal -->");
    document.writeln("                <div class=\'modal fade\' id=\'exampleModal\' tabindex=\'-1\' role=\'dialog\'");
    document.writeln("                    aria-labelledby=\'exampleModalLabel\' aria-hidden=\'true\'>");
    document.writeln("                    <div class=\'modal-dialog\' role=\'document\'>");
    document.writeln("                        <div class=\'modal-content mx-auto w-75\'");
    document.writeln("                            style=\'position: fixed !important;top: 6% !important; left: 10% !important;right: 10% !important;\'>");
    document.writeln("                            <div class=\'modal-header\'");
    document.writeln("                                style=\'background: linear-gradient(180deg, #2278E0 0%, #1754A7 100%);\'>");
    document.writeln("                                <h2 class=\'modal-title text-light m-auto\' id=\'exampleModalLabel\'");
    document.writeln("                                    style=\'font-size: 1.2rem !important;\'>聯繫我們");
    document.writeln("                                </h2>");
    document.writeln("                            </div>");
    document.writeln("                            <div class=\'modal-body p-0\'>");
    document.writeln("                                <img src=\'../img/手機index_img/24HR客服.png\' alt=\'\' class=\'w-100\'>");
    document.writeln("                            </div>");
    document.writeln("                            <div class=\'w-100 \' style=\'background: #555;\'>");
    document.writeln("                                <div class=\'py-2 text-light text-center\' data-dismiss=\'modal\'>Close</div>");
    document.writeln("                            </div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("    <!-- /////////////////////////////////////// 手機板header ///////////////////////////////////// -->");
    document.writeln("");
    document.writeln("    <!-- 金色顏色條 -->");
    document.writeln("    <div class=\'container-fluid p-0\'>");
    document.writeln("        <div class=\'GoldenBorder d-none d-md-block\'></div>");
    document.writeln("        <div class=\'GoldenBorder-md d-md-none\'></div>");
    document.writeln("    </div>");
    document.writeln("    <!-- 金色顏色條 -->");
    document.writeln("    <!-- 跑馬燈 -->");
    document.writeln("    <div class=\'container-fluid p-0 md-footer-color\'>");
    document.writeln("        <div class=\'container\' style=\'position: relative;\'>");
    document.writeln("            <!-- 維修按鈕 -->");
    document.writeln("            <div class=\'dropdown\' style=\'z-index: 999;position: absolute;top: 0;left: 0;\'>");
    document.writeln("                <button class=\'btn Maintenance\' style=\'z-index: 999;top: 0;left: 0;\' type=\'button\' id=\'dropdownMenu2\'");
    document.writeln("                    data-toggle=\'dropdown\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
    document.writeln("                </button>");
    document.writeln("                <div class=\'dropdown-menu\' aria-labelledby=\'dropdownMenu2\' style=\'background-color: #1754A7;\'>");
    document.writeln("                    <button class=\'btn text-light\' type=\'button\' data-toggle=\'modal\' data-target=\'#marqueeBtn\'>");
    document.writeln("                        維修公告1");
    document.writeln("                    </button>");
    document.writeln("                    <button class=\'btn text-light\' type=\'button\' data-toggle=\'modal\' data-target=\'#marqueeBtn2\'>");
    document.writeln("                        維修公告2");
    document.writeln("                    </button>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <!-- 彈出框2 -->");
    document.writeln("            <div class=\'modal fade\' id=\'marqueeBtn2\' tabindex=\'-1\' role=\'dialog\'");
    document.writeln("                aria-labelledby=\'exampleModalCenterTitle\' aria-hidden=\'true\'>");
    document.writeln("                <div class=\'modal-dialog modal-dialog-centered\' role=\'document\'>");
    document.writeln("                    <div class=\'modal-content\'>");
    document.writeln("                        <div class=\'modal-header md-footer-color\'>");
    document.writeln("                            <h2 class=\'modal-title mx-auto text-light\' id=\'exampleModalCenterTitle\'>存款公告</h2>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'modal-body p-5 text-light\' style=\'background: rgb(52, 96, 177);\'>");
    document.writeln("                            開通超商存款後以第一次繳費地點為綁定超商，若後續要更換繳費超商，請先提前告知與客服申請，否則導致造成資金損失風險需自行承擔，若為附近的超商地點繳費提前告知即可");
    document.writeln("                            開通超商存款後以第一次繳費地點為綁定超商，若後續要更換繳費超商，請先提前告知與客服申請，否則導致造成資金損失風險需自行承擔，若為附近的超商地點繳費提前告知即可");
    document.writeln("                        </div>");
    document.writeln("                        <button type=\'button\' class=\'btn btn-secondary\' data-dismiss=\'modal\'>Close</button>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <!-- 彈出框1 -->");
    document.writeln("            <div class=\'modal fade\' id=\'marqueeBtn\' tabindex=\'-1\' role=\'dialog\'");
    document.writeln("                aria-labelledby=\'exampleModalCenterTitle\' aria-hidden=\'true\'>");
    document.writeln("                <div class=\'modal-dialog modal-dialog-centered\' role=\'document\'>");
    document.writeln("                    <div class=\'modal-content\'>");
    document.writeln("                        <div class=\'modal-header md-footer-color\'>");
    document.writeln("                            <h2 class=\'modal-title mx-auto text-light\' id=\'exampleModalCenterTitle\'>維護公告</h2>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'modal-body p-5 text-light\' style=\'background: rgb(52, 96, 177);\'>");
    document.writeln("                            親愛的娛樂城會員您好，【幸運棋牌-維護通知】即刻起進行線路調整緊急維護，維護完成時間待定，造成不便敬請見諒");
    document.writeln("                            親愛的娛樂城會員您好，【幸運棋牌-維護通知】即刻起進行線路調整緊急維護，維護完成時間待定，造成不便敬請見諒");
    document.writeln("                        </div>");
    document.writeln("                        <button type=\'button\' class=\'btn btn-secondary\' data-dismiss=\'modal\'>Close</button>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <!-- 字 -->");
    document.writeln("            <div class=\'\' style=\'z-index: 1;\'>");
    document.writeln("                <marquee direction=\'left\' height=\'30\' scrollamount=\'5\' behavior=\'left\'");
    document.writeln("                    style=\'height: 100%;width: 100%; color: cornsilk;\'>");
    document.writeln("                    【維護公告】 親愛的娛樂城會員您好，【幸運棋牌-維護通知】即刻起進行線路調整緊急維護，維護完成時間待定，造成不便敬請見諒    【存款公告】");
    document.writeln("                    開通超商存款後以第一次繳費地點為綁定超商，若後續要更換繳費超商，請先提前告知與客服申請，否則導致造成資金損失風險需自行承擔，若為附近的超商地點繳費提前告知即可    【存款公告】");
    document.writeln("                    敬愛的卡利會員您好，卡利娛樂城為防堵詐騙氾濫、保障會員資金安全，在此提醒：信用卡、ATM轉帳、VIP專用帳戶存款等服務，務必使用「本人帳戶」！若使用非本人帳戶存款，將一律扣除處理費用後退還本金，感謝您的配合。    【維護公告】");
    document.writeln("                    親愛的會員您好，AV影城將於2020/12/14正式下架，造成不便敬請見諒。    【取款公告】");
    document.writeln("                    親愛的卡利會員您好，由於體育注單會因改判賽事等因素，而進行注單重新結算，因此即日起，卡利娛樂城進行出款時，體育相關注單須全數派彩完畢才處理支付款項，若玩家手上有未派彩注單，麻煩您耐心等候，如有相關疑問、歡迎諮詢24H線上客服，謝謝您。");
    document.writeln("                </marquee>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("    <!-- 跑馬燈 -->");
    document.writeln("    <!-- /////////////////////////////////////// 電腦板 ///////////////////////////////////// -->");
}
// 登入頁面 上方
function indexLoginHeader() {
    document.writeln("<!-- /////////////////////////////////////// 手機板header ///////////////////////////////////// -->");
    document.writeln("<div class=\'container-fluid p-0 d-lg-none \' style=\'background: linear-gradient(180deg, #2278E0 0%, #1754A7 100%);\'>");
    document.writeln("    <div class=\'container\'>");
    document.writeln("        <div class=\'row py-2\' style=\'align-items: center;\'>");
    document.writeln("            <!-- 漢堡圖 -->");
    document.writeln("            <div class=\'col-4 text-left\'>");
    document.writeln("                <!-- HamburgBtn -->");
    document.writeln("                <i class=\'fas fa-bars fa-2x text-light\' id=\'HamburgBtn\' data-toggle=\'modal\'");
    document.writeln("                    data-target=\'#exampleModal0\'></i>");
    document.writeln("                <!--  -->");
    document.writeln("                <div class=\'modal\' id=\'exampleModal0\'>");
    document.writeln("                    <div id=\'showMenu p-0\' class=\'modal-dialog\'>");
    document.writeln("                        <div class=\'showMenuList modal-content\'>");
    document.writeln("                            <div class=\'modal-body p-0\'>");
    document.writeln("                                <!-- 關閉 -->");
    document.writeln("                                <div class=\'w-100\'>");
    document.writeln("                                    <div class=\'pb-2 pt-1 pr-3 text-light text-right\' data-dismiss=\'modal\'><i");
    document.writeln("                                            class=\'fas fa-times text-light\'></i></div>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- user -->");
    document.writeln("                                <div class=\'col-12 text-center w-100\'>");
    document.writeln("                                    <img src=\'../img/手機index_img/sidebar/user.png\' alt=\'\'>");
    document.writeln("                                    <p class=\'text-center text-light pt-1\' style=\'font-size: 1.2rem;\'>admin</p>");
    document.writeln("                                </div>");
    document.writeln("                                <div class=\'sidebarLine w-100\'></div>");
    document.writeln("                                <div class=\'row\'>");
    document.writeln("                                    <div class=\'col-12 pt-3\'><a href=\'../page/Promotion.html\'><img");
    document.writeln("                                                src=\'../img/手機index_img/sidebar/Group 2/1gift.png\' alt=\'\'");
    document.writeln("                                                class=\'pl-3\'><span class=\'text-light pl-3\'>優惠活動</span></a></div>");
    document.writeln("                                    <div class=\'col-12  pt-3\'><a href=\'../header page/Announcement.html\'><img");
    document.writeln("                                                src=\'../img/手機index_img/sidebar/Group 2/2Shape.png\' alt=\'\'");
    document.writeln("                                                class=\'pl-3\'><span class=\'text-light pl-3\'>公告</span></a></div>");
    document.writeln("                                    <div class=\'col-12  pt-3\'><a href=\'../header page/FAQ.html\'><img");
    document.writeln("                                                src=\'../img/手機index_img/sidebar/Group 2/3_question-square-light.png\'");
    document.writeln("                                                alt=\'\' class=\'pl-3\'><span class=\'text-light pl-3\'>常見問題</span></a>");
    document.writeln("                                    </div>");
    document.writeln("                                    <div class=\'col-12  pt-3\'><a href=\'../Features page/RepairTime.html\'><img");
    document.writeln("                                                src=\'../img/手機index_img/sidebar/Group 2/4_clock-light.png\' alt=\'\'");
    document.writeln("                                                class=\'pl-3\'><span class=\'text-light pl-3\'>維修時間</span></a></div>");
    document.writeln("                                    <div class=\'col-12  pt-3\'><a href=\'../header page/AppDownload.html\'><img");
    document.writeln("                                                src=\'../img/手機index_img/sidebar/Group 2/5cloud-download-light.png\'");
    document.writeln("                                                alt=\'\' class=\'pl-3\'><span class=\'text-light pl-3\'>APP下載</span></a>");
    document.writeln("                                    </div>");
    document.writeln("                                    <!-- sidebarBLine -->");
    document.writeln("                                    <div class=\' col-12 py-3\'>");
    document.writeln("                                        <div class=\'sidebarBLine\'></div>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- list2 -->");
    document.writeln("                                <div class=\'row\'>");
    document.writeln("                                    <div class=\'col-12 pt-1\'><a href=\'../Features page/AccessFlow.html\'><img");
    document.writeln("                                                src=\'../img/手機index_img/sidebar/Group 3/1wallet-light.png\' alt=\'\'");
    document.writeln("                                                class=\'pl-3\'><span class=\'text-light pl-3\'>存取流程</span></a></div>");
    document.writeln("                                    <div class=\'col-12  pt-3\'><a href=\'../header page/Agent.html\'><img");
    document.writeln("                                                src=\'../img/手機index_img/sidebar/Group 3/5_cooperation.png\' alt=\'\'");
    document.writeln("                                                class=\'pl-3\'><span class=\'text-light pl-3\'>合營代理</span></a></div>");
    document.writeln("                                    <div class=\'col-12  pt-3\'><a href=\'../Features page/AboutUs.html\'><img");
    document.writeln("                                                src=\'../img/手機index_img/sidebar/Group 3/6_RENNIBO1.png\' alt=\'\'");
    document.writeln("                                                class=\'pl-3\'><span class=\'text-light pl-3\'>關於任你博</span></a></div>");
    document.writeln("                                    <!-- sidebarBLine -->");
    document.writeln("                                    <div class=\' col-12 py-3\'>");
    document.writeln("                                        <div class=\'sidebarBLine\'></div>");
    document.writeln("                                    </div>");
    document.writeln("                                </div>");
    document.writeln("                                <!-- list3 -->");
    document.writeln("                                <div class=\'row\'>");
    document.writeln("                                    <div class=\'col-12 pt-1\'><a href=\'../index.html\' role=\'button\'><img");
    document.writeln("                                                src=\'../img/手機index_img/sidebar/signOut.png\' alt=\'\'");
    document.writeln("                                                class=\'pl-3\'><span class=\'text-light pl-3\'>登出</span></a></div>");
    document.writeln("                                </div>");
    document.writeln("                            </div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'col-4 text-center\'>");
    document.writeln("                <div class=\'text-center\' style=\'margin-left: -5%;\'><a href=\'../index.html\'><img");
    document.writeln("                            src=\'../img/桌機index_img/logo.png\' alt=\'\' class=\'w-100\'></a></div>");
    document.writeln("            </div>");
    document.writeln("            <!-- 24HR客服 -->");
    document.writeln("            <div class=\'col-4\'>");
    document.writeln("                <div class=\'text-right\' style=\'margin-right: 10%;\'><img id=\'hrServiceBtn\'");
    document.writeln("                        src=\'../img/手機index_img/24-service.png\' alt=\'\' class=\'h-100\' data-toggle=\'modal\'");
    document.writeln("                        data-target=\'#exampleModal\'></div>");
    document.writeln("            </div>");
    document.writeln("            <!-- Modal -->");
    document.writeln("            <div class=\'modal fade\' id=\'exampleModal\' tabindex=\'-1\' role=\'dialog\'");
    document.writeln("                aria-labelledby=\'exampleModalLabel\' aria-hidden=\'true\'>");
    document.writeln("                <div class=\'modal-dialog\' role=\'document\'>");
    document.writeln("                    <div class=\'modal-content mx-auto w-75\'");
    document.writeln("                        style=\'position: fixed !important;top: 6% !important; left: 10% !important;right: 10% !important;\'>");
    document.writeln("                        <div class=\'modal-header\'");
    document.writeln("                            style=\'background: linear-gradient(180deg, #2278E0 0%, #1754A7 100%);\'>");
    document.writeln("                            <h2 class=\'modal-title text-light m-auto\' id=\'exampleModalLabel\'");
    document.writeln("                                style=\'font-size: 1.2rem !important;\'>聯繫我們");
    document.writeln("                            </h2>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'modal-body p-0\'>");
    document.writeln("                            <img src=\'../img/手機index_img/24HR客服.png\' alt=\'\' class=\'w-100\'>");
    document.writeln("                        </div>");
    document.writeln("                        <div class=\'w-100 \' style=\'background: #555;\'>");
    document.writeln("                            <div class=\'py-2 text-light text-center\' data-dismiss=\'modal\'>Close</div>");
    document.writeln("                        </div>");
    document.writeln("                    </div>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln("<!-- 金色顏色條 -->");
    document.writeln("<div class=\'container-fluid p-0\'>");
    document.writeln("    <div class=\'GoldenBorder d-none d-md-block\'></div>");
    document.writeln("    <div class=\'GoldenBorder-md d-md-none\'></div>");
    document.writeln("</div>");
    document.writeln("<!-- 跑馬燈 -->");
    document.writeln("<div class=\'container-fluid p-0 md-footer-color\'>");
    document.writeln("    <div class=\'container\' style=\'position: relative;\'>");
    document.writeln("        <!-- 維修按鈕 -->");
    document.writeln("        <div class=\'dropdown\' style=\'z-index: 999;position: absolute;top: 0;left: 0;\'>");
    document.writeln("            <button class=\'btn Maintenance\' style=\'z-index: 999;top: 0;left: 0;\' type=\'button\' id=\'dropdownMenu2\'");
    document.writeln("                data-toggle=\'dropdown\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
    document.writeln("            </button>");
    document.writeln("            <div class=\'dropdown-menu\' aria-labelledby=\'dropdownMenu2\' style=\'background-color: #1754A7;\'>");
    document.writeln("                <button class=\'btn text-light\' type=\'button\' data-toggle=\'modal\' data-target=\'#marqueeBtn\'>");
    document.writeln("                    維修公告1");
    document.writeln("                </button>");
    document.writeln("                <button class=\'btn text-light\' type=\'button\' data-toggle=\'modal\' data-target=\'#marqueeBtn2\'>");
    document.writeln("                    維修公告2");
    document.writeln("                </button>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("        <!-- 彈出框2 -->");
    document.writeln("        <div class=\'modal fade\' id=\'marqueeBtn2\' tabindex=\'-1\' role=\'dialog\'");
    document.writeln("            aria-labelledby=\'exampleModalCenterTitle\' aria-hidden=\'true\'>");
    document.writeln("            <div class=\'modal-dialog modal-dialog-centered\' role=\'document\'>");
    document.writeln("                <div class=\'modal-content\'>");
    document.writeln("                    <div class=\'modal-header md-footer-color\'>");
    document.writeln("                        <h2 class=\'modal-title mx-auto text-light\' id=\'exampleModalCenterTitle\'>存款公告</h2>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'modal-body p-5 text-light\' style=\'background: rgb(52, 96, 177);\'>");
    document.writeln("                        開通超商存款後以第一次繳費地點為綁定超商，若後續要更換繳費超商，請先提前告知與客服申請，否則導致造成資金損失風險需自行承擔，若為附近的超商地點繳費提前告知即可");
    document.writeln("                        開通超商存款後以第一次繳費地點為綁定超商，若後續要更換繳費超商，請先提前告知與客服申請，否則導致造成資金損失風險需自行承擔，若為附近的超商地點繳費提前告知即可");
    document.writeln("                    </div>");
    document.writeln("                    <button type=\'button\' class=\'btn btn-secondary\' data-dismiss=\'modal\'>Close</button>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("        <!-- 彈出框1 -->");
    document.writeln("        <div class=\'modal fade\' id=\'marqueeBtn\' tabindex=\'-1\' role=\'dialog\'");
    document.writeln("            aria-labelledby=\'exampleModalCenterTitle\' aria-hidden=\'true\'>");
    document.writeln("            <div class=\'modal-dialog modal-dialog-centered\' role=\'document\'>");
    document.writeln("                <div class=\'modal-content\'>");
    document.writeln("                    <div class=\'modal-header md-footer-color\'>");
    document.writeln("                        <h2 class=\'modal-title mx-auto text-light\' id=\'exampleModalCenterTitle\'>維護公告</h2>");
    document.writeln("                    </div>");
    document.writeln("                    <div class=\'modal-body p-5 text-light\' style=\'background: rgb(52, 96, 177);\'>");
    document.writeln("                        親愛的娛樂城會員您好，【幸運棋牌-維護通知】即刻起進行線路調整緊急維護，維護完成時間待定，造成不便敬請見諒");
    document.writeln("                        親愛的娛樂城會員您好，【幸運棋牌-維護通知】即刻起進行線路調整緊急維護，維護完成時間待定，造成不便敬請見諒");
    document.writeln("                    </div>");
    document.writeln("                    <button type=\'button\' class=\'btn btn-secondary\' data-dismiss=\'modal\'>Close</button>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("        <!-- 字 -->");
    document.writeln("        <div class=\'\' style=\'z-index: 1;\'>");
    document.writeln("            <marquee direction=\'left\' height=\'30\' scrollamount=\'5\' behavior=\'left\'");
    document.writeln("                style=\'height: 100%;width: 100%; color: cornsilk;\'>");
    document.writeln("                【維護公告】 親愛的娛樂城會員您好，【幸運棋牌-維護通知】即刻起進行線路調整緊急維護，維護完成時間待定，造成不便敬請見諒    【存款公告】");
    document.writeln("                開通超商存款後以第一次繳費地點為綁定超商，若後續要更換繳費超商，請先提前告知與客服申請，否則導致造成資金損失風險需自行承擔，若為附近的超商地點繳費提前告知即可    【存款公告】");
    document.writeln("                敬愛的卡利會員您好，卡利娛樂城為防堵詐騙氾濫、保障會員資金安全，在此提醒：信用卡、ATM轉帳、VIP專用帳戶存款等服務，務必使用「本人帳戶」！若使用非本人帳戶存款，將一律扣除處理費用後退還本金，感謝您的配合。    【維護公告】");
    document.writeln("                親愛的會員您好，AV影城將於2020/12/14正式下架，造成不便敬請見諒。    【取款公告】");
    document.writeln("                親愛的卡利會員您好，由於體育注單會因改判賽事等因素，而進行注單重新結算，因此即日起，卡利娛樂城進行出款時，體育相關注單須全數派彩完畢才處理支付款項，若玩家手上有未派彩注單，麻煩您耐心等候，如有相關疑問、歡迎諮詢24H線上客服，謝謝您。");
    document.writeln("            </marquee>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("</div>");
    document.writeln("<div class=\'container-fluid d-md-none p-0 m-0 FAQ-btn-items\'>");
    document.writeln("    <div class=\'row p-0 m-0 border-bottom border-warning\'>");
    document.writeln("        <div class=\'col p-2\'>");
    document.writeln("            <div class=\'col-12\'>");
    document.writeln("                <span class=\'list-inline-item\'>您好,</span>");
    document.writeln("                <span class=\'list-inline-item\'>user</span>");
    document.writeln("            </div>");
    document.writeln("            <div class=\'col-12\'>");
    document.writeln("                <i class=\'fas fa-star fa-sm text-warning\'></i>");
    document.writeln("                <i class=\'far fa-star fa-sm\'></i>");
    document.writeln("                <i class=\'far fa-star fa-sm\'></i>");
    document.writeln("                <i class=\'far fa-star fa-sm\'></i>");
    document.writeln("                <i class=\'far fa-star fa-sm\'></i>");
    document.writeln("                <i class=\'far fa-star fa-sm\'></i>");
    document.writeln("            </div>");
    document.writeln("");
    document.writeln("        </div>");
    document.writeln("        <div class=\'col\'>");
    document.writeln("            <div class=\'col-12 text-right pt-3\'>");
    document.writeln("                <a href=\'../Features page/MemberNotification.html\'>");
    document.writeln("                    <i class=\'fas fa-bell text-light\'></i>");
    document.writeln("                </a>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("    <div class=\'row p-0 m-0\'>");
    document.writeln("        <div class=\'col p-2\'>");
    document.writeln("            <div class=\'col-12\'>");
    document.writeln("                <img src=\'../img/登入條/money.png\' alt=\'\' class=\'img-fluid\'>");
    document.writeln("                <span>1,000,000</span>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("");
    document.writeln("    </div>");
    document.writeln("</div>");
}
// 登入頁面 Footer
function indexLoginFooter() {
    document.writeln("<!-- footer h -->");
    document.writeln("    <div class=\'container-fluid d-md-none\' id=\'footerH\'></div>");
    document.writeln("        ");
    document.writeln("    <!-- footer -->");
    document.writeln("    <div class=\'container-fluid d-md-none md-footer-color fixed-bottom\' id=\'footerHC\'>");
    document.writeln("        <div class=\'row py-2\'>");
    document.writeln("            <div class=\'col text-center\'><a href=\'../index.html\'><img class=\'w-100\'");
    document.writeln("                        src=\'../img/手機index_img/手機最下方/包裝/首頁登入.png\' alt=\'\'></a></div>");
    document.writeln("            <div class=\'col text-center\'><a href=\'../Features page/PlatformTransfer.html\'><img class=\'w-100\' src=\'../img/手機index_img/手機最下方/包裝/平台轉帳.png\'");
    document.writeln("                        alt=\'\'></a></div>");
    document.writeln("            <div class=\'col text-center\'><a href=\'../Features page/DepositWthdrawal.html\'><img class=\'w-100\' src=\'../img/手機index_img/手機最下方/包裝/存款_提款.png\'");
    document.writeln("                        alt=\'\'></a></div>");
    document.writeln("            <div class=\'col text-center\'><a href=\'../page/Promotion.html\'><img class=\'w-100\'");
    document.writeln("                        src=\'../img/手機index_img/手機最下方/包裝/優惠活動.png\' alt=\'\'></a></div>");
    document.writeln("            <div class=\'col text-center\'><a href=\'../Features page/MemberCentre.html\'><img class=\'w-100\' src=\'../img/手機index_img/手機最下方/包裝/會員中心.png\'");
    document.writeln("                        alt=\'\'></a></div>");
    document.writeln("        </div>");
    document.writeln("    </div>");
    document.writeln("    <script src=\'../js/footerH.js\'></script>");
}